# avrtmon
# Makefile - < Here goes a description of this specific makefiles >
# Uses the rules defined by Prof. Giorgio Grisetti in the file 'avr.mk'
# NOTE: With vim, you can easily substitute a <...> snippet by going in its line
#   and typing (do not count spaces):
#     ESC f< cf>
# Paolo Lucchesi - Tue 06 Aug 2019 02:27:30 AM CEST
# TODO: Learn to use GNU Make better to make a better GNU Make makefile :D

# Executable files containing the 'main' routine
BINS = 

# Object files to be generated by GNU Make
OBJECTS = 

# Additional head files not included in the head directory
HEADERS = 


test_crc:
	$(call host_test,$@,sources/crc.c)

test_packet:
	$(call host_test,$@,sources/packet.c sources/crc.c)

test_serial: tests/serial_test.hex
	# TODO: Write an automated test for host-side
	# TODO: Provide also 'serial.o' object file

# Test (from the PC's OS) a module of the project
# Tests are performed by performing:
#   $(call host_test test_name, additional source files list)
# The function expect to find a source file named 'tests/<test_name>.c'
# You can also choose a test method defining the variable 'TEST_WITH' in your
# shell. Supported option are none (i.e. execute as-is), 'gdb' and 'less'
define host_test =
	gcc $(INCLUDE) -DDEBUG -ggdb -o tests/bin/$(1) tests/$(1).c $(2)
	@if   [ '$(TEST_WITH)' == ''     ]; then \
		tests/bin/$(1);	\
	elif [ '$(TEST_WITH)' == 'less' ]; then \
		tests/bin/$(1) | less -F; \
	elif [ '$(TEST_WITH)' == 'gdb'  ]; then \
		gdb tests/bin/$(1); \
	fi
	rm tests/bin/$(1)
endef


# This does the magick
include ./resources/gnu-make/avr.mk
